const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const root = path.resolve(__dirname, '../build');
const home = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'));
const editor = new JSDOM(fs.readFileSync(path.join(root, 'create/index.html'), 'utf8'));
const doc = home.window.document;
const canonical = doc.querySelector('link[rel="canonical"]').href;
assert.equal(doc.querySelectorAll('link[rel="canonical"]').length, 1);
assert.equal(doc.querySelectorAll('h1').length, 1);
assert.ok(doc.querySelector('main').textContent.includes('Veyfolio'));
assert.ok(doc.querySelector('a[href="/create"]'));
assert.equal(doc.querySelector('meta[name="robots"]').content, 'index, follow, max-image-preview:large');
assert.equal(editor.window.document.querySelector('meta[name="robots"]').content, 'noindex, follow');
assert.equal(editor.window.document.querySelector('link[rel="canonical"]').href, new URL('/create', canonical).href);
assert.equal(editor.window.document.getElementById('root').textContent, '');
assert.equal(JSON.parse(doc.querySelector('#veyfolio-schema').textContent).url, canonical);
assert.equal(doc.querySelector('meta[name="twitter:card"]').content, 'summary_large_image');
const imageUrl = new URL(doc.querySelector('meta[property="og:image"]').content);
assert.equal(imageUrl.origin, new URL(canonical).origin);
assert.ok(fs.existsSync(path.join(root, imageUrl.pathname)));
const sitemap = new JSDOM(fs.readFileSync(path.join(root, 'sitemap.xml'), 'utf8'), { contentType: 'application/xml' });
assert.deepEqual([...sitemap.window.document.querySelectorAll('loc')].map(node => node.textContent), [canonical]);
assert.ok(fs.readFileSync(path.join(root, 'robots.txt'), 'utf8').includes(`Sitemap: ${new URL('/sitemap.xml', canonical).href}`));
home.window.close();
editor.window.close();
sitemap.window.close();
console.log('SEO output checks passed: content, canonical, schema, social image, editor noindex and crawler files.');
